#student_name = input("enter your name ")
#print(student_name)
#num1 = input("enter you first number :")
#num2 =  input("enter your second number :")
#print(num1 +num2)
#num1 = int(input("enter you first name :"))
#num2 = int(input("enter you second number :"))
#print(num1 +num2)
#num1 = float(input("enter you first name :"))
#num2 = float(input("enter you second number :"))
#sum = num1 +num2
#print(sum)
#num1 = float(input("enter you first name :"))
#num2 = float(input("enter you second number :"))
#print(f" the sum  of {num1} and {num2}is sum:")
#print(f" the sum of {num1} and {num2} is {num1 + num2}:")

#num1 = list(input("enter you first name :"))
#num2 = list(input("enter you second number :"))
#print(num1 + num2)
